### ISSUE TITLE
Better error handling on connection block

### ISSUE THREAD

**Issue by Robot-In-A-Can** [Robot-In-A-Can/eBrain-Snap#6]
- Check if serial communication is available on the device
- Check if websocket is available
- Check if the connection is secure
- throw an error in a balloon and/or as morphic alert
- add timeout to wait-until so connection block can fail gracefully and give feedback as to why it didn't connect

**Comment by vexandmore** [comment]
This should be done now

**Comment by opencoca** [comment]
Thanks for the work on this @vexandmore
